### ISSUE TITLE
keep left side menu status

### ISSUE THREAD

**Issue by myguddy** [cnpst/zcp-portal-ui#11]
App/[Deployment/StatefulSet...]/ 
operate something in the view and when refresh view, the left menu closed.

Need to keep left menu status(open/close) in order to indicate the current feature.

**Comment by mdiver** [comment]
sidemenu가 close되는 것이 아니라
Deployment / StatefulSet 등의 목록에서 선택 시 해당 내용으로 sidemenu가 이동되는 것 같습니다.

보통은 연결되는 것이 없어서 sidemenu에서 메뉴선택이 안 되지만
Deployment에서 zcp-system의 alertmanager를 선택하시면 아래와 같이 sidemenu 중 알림이 활성화되는 것을 보실 수 있습니다.
![2019-02-19 3 20 19](https://user-images.githubusercontent.com/37290743/52994176-137a6480-345a-11e9-82a3-800202c543ab.png)

목록에서 선택하여 상세내용으로 넘어갈 때 sidemenu와 연결되는 것을 끊고 App메뉴가 계속 선택되어 있도록 변경이 필요할 것으로 보여집니다.

**Comment by yanghoon** [comment]
@mdiver Wmm… No, it is correct to side menus is closed.
My expectation does not change side menus at details.
Your experience is just accident, cause URL prefix of details is matched with URL of “알림”. (or you open it)
@myguddy I will reorganize URLs. :)
