### ISSUE TITLE
알림 - Channel 화면에서 신규 채널 생성 시 생성되었다고 하고 화면에 보이지 않음

### ISSUE THREAD

**Issue by mdiver** [cnpst/zcp-portal-ui#17]
신규 채널을 생성하였는데 아래와 같이 생성되었다고 확인되지만
![2019-02-19 1 54 37](https://user-images.githubusercontent.com/37290743/52991028-2b4beb80-344e-11e9-9dae-d542d2168d21.png)

실질적으로 화면의 채널 목록에 신규생성한 채널이 보이지 않습니다.
![2019-02-19 1 55 39](https://user-images.githubusercontent.com/37290743/52991037-3a329e00-344e-11e9-8e49-3fe1eb8342e2.png)

또한 신규 Rule 추가 시에도 선택할 수 있는 채널에서 보여지지 않습니다.
![2019-02-19 1 55 50](https://user-images.githubusercontent.com/37290743/52991056-5afaf380-344e-11e9-909a-58ed86d22e73.png)

ps. 테스트 신규채널명은 test12, test22 등과 같은 채널명을 사용하였습니다.

**Comment by yanghoon** [comment]
console.cloudzcp.io 가 설치된 네임스페이스에는 현재 zcp-alertmanager 는 연동 되어있지 않습니다.
테스트 안하셔도 무방하고, 필요시 pod-dev-console.cloudzcp.io 에서 테스트 부탁드립니다 (_ _)
