### ISSUE TITLE
상세화면 -> 목록 이동시 메뉴별 ux가 다름

### ISSUE THREAD

**Issue by yoomisun2** [cnpst/zcp-portal-ui#18]
- App,Network,Resource,Storage 메뉴는 아래 그림과 같이 화살표 클릭으로 이동
![k-002](https://user-images.githubusercontent.com/37431665/52991045-4a4a7d80-344e-11e9-8efe-929c1ef81efa.png)

- Cluster 관리 메뉴는 '목록으로 돌아가기' 텍스트 클릭으로 이동
![k-003](https://user-images.githubusercontent.com/37431665/52991103-91d10980-344e-11e9-9325-e4c34453090e.png)

**Comment by yanghoon** [comment]
console.cloudzcp.io 가 설치된 네임스페이스에는 현재 zcp-alertmanager 는 연동 되어있지 않습니다.
필요시 pod-dev-console.cloudzcp.io 에서 테스트 하시면 될 것 같습니다.
