### ISSUE TITLE
기본 콘솔과 신규 추가된 Pod 콘솔 브라우져 타이들이 다름

### ISSUE THREAD

**Issue by billygoo** [cnpst/zcp-portal-ui#4]
브라우져에 노출되는 이름이 메뉴에 따라 다른 타이틀로 표시됩니다.

- 기존 최초 타이틀 : CloudZ CP([클러스터명] - 메인
- 신규 메뉴 타이틀 : Kubernetes Main

**Comment by yanghoon** [comment]
https://stackoverflow.com/a/36614819
