### ISSUE TITLE
Console에서 GIT으로 링크를 통해 바로 넘어갈때 SSO 연결이 안됨

### ISSUE THREAD

**Issue by lay126** [cnpst/zcp-portal-ui#50]
Console에서 GIT으로 링크를 통해 바로 넘어갈때 SSO 연결이 안됨
- Console에서 Git Add-on 링크로 넘어갈때, SSO연결이 동작하지 않음. 일반 로그인으로 로그인 할때는 됨.

**Comment by jigyoomin** [comment]
보통 두 가지 방법으로 해결됨.
1. 인증 정보 갱신
  - Gitea 에 어드민 계정으로 로그인
  - 우측 상단 메뉴 - 관리자 패널 - 인증 - keycloak
  - 정보 확인 후 update 버튼을 눌러서 저장
  * 변경할 정보가 없더라도 반드시 update 버튼을 한번 눌러줄 것
인증 정보 갱신으로 해결되지 않을 경우 2번 시도
2. 사용자 계정 연동 재시도
  - Gitea 에 어드민 계정으로 로그인
  - 우측 상단 메뉴 - 관리자 패널 - 사용자
  - 해당 사용자 우측의 수정 버튼 클릭
  - 인증 소스를 로컬로 지정 후 저장
  - 해당 사용자로 로그인 후 SSO 연결 시도
  - Gitea 로그인
