### ISSUE TITLE
제조통합플랫폼 설치 후 이슈

### ISSUE THREAD

**Issue by mdiver** [cnpst/zcp-portal-ui#55]
제조통합플랫폼 설치 후 아래와 같이 에러가 발생한 것을 확인했습니다.

1. Notifications > Channel
![스크린샷 2019-06-17 17 34 25](https://user-images.githubusercontent.com/37290743/59590196-7937de00-9126-11e9-8cda-2e05952a0b1a.png)

2. Notifications > Rules
![스크린샷 2019-06-17 17 33 58](https://user-images.githubusercontent.com/37290743/59590204-7d63fb80-9126-11e9-8995-74c79aef9049.png)

3. DevOps > Code
![스크린샷 2019-06-17 17 34 39](https://user-images.githubusercontent.com/37290743/59590214-80f78280-9126-11e9-8066-0f1919fda0e8.png)

**Comment by lay126** [comment]
Identified as installation issues
