### ISSUE TITLE
Alerting 화면 접속시 서버에러 내용이 팝업으로 뜸

### ISSUE THREAD

**Issue by yoomisun2** [cnpst/zcp-portal-ui#9]
![k-001](https://user-images.githubusercontent.com/37431665/52990535-f50d6c80-344b-11e9-9df6-406c36c935e4.png)

**Comment by yanghoon** [comment]
console.cloudzcp.io 가 설치된 네임스페이스에는 현재 zcp-alertmanager 는 연동 되어있지 않습니다.
테스트 안하셔도 무방하고, 필요시 pod-dev-console.cloudzcp.io 에서 테스트 부탁드립니다 (_ _)
